ARG AIRFLOW_IMAGE=apache/airflow:2.7.1-python3.10
FROM ${AIRFLOW_IMAGE}

# Passe en root pour installer d'éventuels paquets système (exemple libpq-dev)
USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc libpq-dev && \
    rm -rf /var/lib/apt/lists/*

# Repassage en airflow pour pip install (conseillé par la doc)
USER airflow
RUN pip install --no-cache-dir \
    apache-airflow-providers-amazon \
    apache-airflow-providers-postgres

# On reste en airflow pour exécuter Airflow
USER airflow
