# docker-compose.yml
services:

  minio:
    image: minio/minio:latest
    env_file: .env
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    restart: always
    healthcheck:
      test: ["CMD", "sh", "-c", "mc alias set myminio http://localhost:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD} && mc admin info myminio"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres:
    image: postgres:13
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql:ro
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
    depends_on: [postgres]
    env_file: .env
    working_dir: /usr/app
    volumes:
      - ./statsbomb_dbt:/usr/app
      - ./dbt_profiles:/root/.dbt
    ports:
      - "8085:8085"
    command: ["docs", "serve", "--port", "8085", "--host", "0.0.0.0"]
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8085/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  superset:
    image: apache/superset:latest
    depends_on: [postgres]
    env_file: .env
    volumes:
      - superset_home:/home/superset
      - ./superset_config.py:/app/pythonpath/superset_config.py:ro
    environment:
      SUPERSET_DATABASE_URI: >-
        postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    ports:
      - "8088:8088"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8088/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # ────────────────────────────────────────────────────────────────────────────
  airflow-image:
    build:
      context: .
      dockerfile: Dockerfile-airflow
    image: data_pipeline_project-airflow:latest

  airflow-init:
    image: data_pipeline_project-airflow:latest
    env_file: .env
    depends_on: [postgres, minio]
    # IMPORTANT : on exporte les mêmes vars que scheduler/webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: >-
        postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      AIRFLOW_CONN_POSTGRES_DEFAULT: >-
        postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      AWS_DEFAULT_REGION: us-east-1
      AIRFLOW__AWS__S3_ENDPOINT_URL: http://minio:9000
    entrypoint: >
      bash -c "
        airflow db upgrade &&
        airflow users create \
          --username admin \
          --firstname Airflow \
          --lastname Admin \
          --role Admin \
          --email admin@example.com \
          --password ${AIRFLOW__WEBSERVER__SECRET_KEY}
      "
    restart: "no"

  airflow-scheduler:
    image: data_pipeline_project-airflow:latest
    depends_on: [airflow-init]
    env_file: .env
    command: ["airflow", "scheduler"]
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./statsbomb_dbt:/opt/airflow/statsbomb_dbt
      - ./dbt_profiles:/opt/airflow/dbt_profiles
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: >-
        postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      AIRFLOW_CONN_POSTGRES_DEFAULT: >-
        postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      AWS_DEFAULT_REGION: us-east-1
      AIRFLOW__AWS__S3_ENDPOINT_URL: http://minio:9000
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "airflow jobs check --job-type SchedulerJob || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  airflow-webserver:
    image: data_pipeline_project-airflow:latest
    depends_on: [airflow-init]
    env_file: .env
    command: ["airflow", "webserver", "--port", "8080"]
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./statsbomb_dbt:/opt/airflow/statsbomb_dbt
      - ./dbt_profiles:/opt/airflow/dbt_profiles
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: >-
        postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      AIRFLOW_CONN_POSTGRES_DEFAULT: >-
        postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      AWS_DEFAULT_REGION: us-east-1
      AIRFLOW__AWS__S3_ENDPOINT_URL: http://minio:9000
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  minio_data:
  postgres_data:
  superset_home:
