version: 2

models:
  - name: stg_events
    description: "Staging des évènements de match"
    columns:
      - name: event_id
        description: "Identifiant unique de l’événement"
      - name: match_id
        description: "Identifiant du match associé"
      - name: period
        description: "Période du match (1=mi-temps 1, 2=mi-temps 2…)"
      - name: event_time
        description: "Heure de l’événement (type TIME) au sein du match"
      - name: minute
        description: "Minute du match (entier)"
      - name: second
        description: "Seconde dans la minute (entier)"
      - name: team_id
        description: "Identifiant de l’équipe réalisant l’action"
      - name: team_name
        description: "Nom de l’équipe réalisant l’action"
      - name: player_id
        description: "Identifiant du joueur (s’il y en a un)"
      - name: player_name
        description: "Nom du joueur"
      - name: position_id
        description: "Identifiant du poste du joueur"
      - name: position_name
        description: "Nom du poste du joueur"
      - name: location_x
        description: "Coordonnée X de l’action sur le terrain"
      - name: location_y
        description: "Coordonnée Y de l’action sur le terrain"
      - name: duration
        description: "Durée de l’événement (secondes), si renseignée"
      - name: under_pressure
        description: "TRUE si le porteur du ballon était sous pression"
      - name: off_camera
        description: "TRUE si l’action était hors caméra"
      - name: play_pattern_id
        description: "Identifiant du pattern de jeu (ex. 8=From Keeper)"
      - name: play_pattern_name
        description: "Nom du pattern de jeu (ex. From Keeper, Throw In, etc.)"
      - name: related_events
        description: "JSONB liste d’UUID d’événements liés"
      - name: event_type
        description: "Type principal d’événement (Pass, Shot, Dribble…)"
      - name: event_details
        description: "JSONB des attributs détaillés non normalisés"
