version: 2

models:
  - name: dim_competition
    description: "Dimension des compétitions"
    columns:
      - name: competition_id
        description: "Identifiant unique de la compétition"
      - name: season_id
        description: "Identifiant de la saison"
      - name: competition_name
        description: "Nom de la compétition"
      - name: competition_gender
        description: "Genre de la compétition"
      - name: country_name
        description: "Pays ou région"
      - name: season_name
        description: "Libellé de la saison"

  - name: dim_team
    description: "Dimension des équipes"
    columns:
      - name: team_id
        description: "Identifiant unique de l’équipe"
      - name: team_name
        description: "Nom de l’équipe"
      - name: team_gender
        description: "Genre de l’équipe"

  - name: dim_player
    description: "Dimension des joueurs"
    columns:
      - name: player_id
        description: "Identifiant unique du joueur"
      - name: player_name
        description: "Nom du joueur"

  - name: dim_date
    description: "Dimension temps"
    columns:
      - name: date
        description: "Date (YYYY-MM-DD)"
      - name: year
        description: "Année"
      - name: month
        description: "Mois (1–12)"
      - name: day
        description: "Jour du mois"
      - name: quarter
        description: "Trimestre (1–4)"
      - name: day_of_year
        description: "Jour de l’année (1–365/366)"
      - name: day_of_week
        description: "Jour ISO de la semaine (1=Lundi…7=Dimanche)"

  - name: fact_event
    description: "Table de fait des événements de match"
    columns:
      - name: event_id
        description: "Identifiant unique de l’événement"
      - name: match_id
        description: "Identifiant du match"
      - name: event_timestamp
        description: "Horodatage complet (date + heure) de l’événement"
      - name: period
        description: "Période du match (1re mi-temps / 2e mi-temps…)"
      - name: event_time
        description: "Heure (type TIME) de l’événement dans le match"
      - name: team_id
        description: "Clé vers dim_team"
      - name: team_name
        description: "Nom de l’équipe"
      - name: player_id
        description: "Clé vers dim_player"
      - name: player_name
        description: "Nom du joueur"
      - name: position_id
        description: "Identifiant du poste du joueur"
      - name: position_name
        description: "Nom du poste du joueur"
      - name: location_x
        description: "Coordonnée X de l’action"
      - name: location_y
        description: "Coordonnée Y de l’action"
      - name: duration
        description: "Durée (en secondes) de l’événement"
      - name: under_pressure
        description: "TRUE si le joueur était sous pression"
      - name: off_camera
        description: "TRUE si l’action était hors caméra"
      - name: play_pattern_id
        description: "Identifiant du pattern de jeu"
      - name: play_pattern_name
        description: "Nom du pattern de jeu"
      - name: related_events
        description: "Liste JSON des événements liés"
      - name: event_type
        description: "Type d’événement (Pass, Shot, Dribble…)"
      - name: event_details
        description: "JSONB des autres attributs non dénormalisés"
